### ISSUE TITLE
Error 167: The given account is not owned by the executing program

### ISSUE THREAD

**Issue by ghost** [VegetarianOrc/sol-nft-staking#3]
Hi,

Have you encountered this error before? What's the best way to debug this? Don't have access to his wallet and can't reproduce on my 4 wallets.

**Error 167: The given account is not owned by the executing program**

One of our users is having trouble unstaking his nfts:

User wallet: [DhnVHatQNgk66JXDtHFtzMWrpe1WVUz6SLqyZQgW2dxH](https://explorer.solana.com/address/DhnVHatQNgk66JXDtHFtzMWrpe1WVUz6SLqyZQgW2dxH)
User PDA staking wallet: [2AVB7nsETgEi9gJR8E67oHKyJQDKR45SjBs4CFrxtb1q](https://explorer.solana.com/address/2AVB7nsETgEi9gJR8E67oHKyJQDKR45SjBs4CFrxtb1q)

![unknown](https://user-images.githubusercontent.com/93984889/148207937-a0609358-0729-4da6-bfee-545e8ac7e564.png)
![unknown (1)](https://user-images.githubusercontent.com/93984889/148208182-24663792-8182-4a12-82e2-a1b7850cde3e.png)

**Comment by VegetarianOrc** [comment]
Hey! I usually find the failed transaction on the block explorer and compare the accounts 1 by 1 to what they're expected to be. It's a bit painful, but it can be helpful. When I've seen something like this happen, it's usually b/c I've passed the wrong account, or an account hasn't been initialized.

Looking at the transaction history for the PDA staking wallet (`2AVB7nsETgEi9gJR8E67oHKyJQDKR45SjBs4CFrxtb1q`), I don't see any failed transactions that returned the 167 error code. Do you have the transaction ID of a failed attempt?

**Comment by ghost** [comment]
that's the issue.. i looked in the explorer as well and no failed transactions. 

pushed a change to log the transactions signature in the browser console, i'll ask the owner to try again and provide the signature

**Comment by ghost** [comment]
Failing with the following error now: **Instruction 0: custom program error: 0xa7**
Can't get a signature.. i assume it doesn't reach the blockchain

Parameters going to the unstake method:

```
{
   "clock":"SysvarC1ock11111111111111111111111111111111",
   "nftMint":"yWW91YHhB2BDHYXzN4AcbAfGR6o87huWfGVAXk8mG7T",
   "nftTokenAccount":"6TQibhnztWmgUoDXXzLPHmcPksySqRBBxsbcbfAEEk2v",
   "owner":"DhnVHatQNgk66JXDtHFtzMWrpe1WVUz6SLqyZQgW2dxH",
   "programId":"4dozACqDarKYdmTV2MMdra6ZDAvNmp49pE6SeDFMafxq",
   "rent":"SysvarRent111111111111111111111111111111111",
   "rewardAuthority":"7SfcozqvXKoEGBAMDVdfCBbLe3tupa2ocpSnaYfmGLgG",
   "rewardMint":"DVPWKGLFHK73PwgKgTtW28iCZGewQdva2N5HeBLDorVJ",
   "rewardTokenAccount":"BL1sQzkozryP3vArrrRuio8E97F6Xjo831N398YoYznw",
   "rewarder":"6pGAhY84XyadDEYhdkZedFh5Lz4A8sWbGzf5EKvCJB4g",
   "rewarderMintAssociatedAccount":"BdXm1rvjzkZbCr9uMLCzETmgyaXuaSGxECV7LdTkB2UZ",
   "stakeAccount":"2AVB7nsETgEi9gJR8E67oHKyJQDKR45SjBs4CFrxtb1q",
   "systemProgram":"11111111111111111111111111111111",
   "tokenProgram":"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
}
```

**Comment by ghost** [comment]
https://discord.com/channels/889577356681945098/889577399308656662/924999081032564758

<img width="1339" alt="Screenshot 2022-01-06 at 17 54 20" src="https://user-images.githubusercontent.com/93984889/148411023-117dc4f6-bff3-48b0-9143-2f25d1af38ed.png">

Seems to be an issue only for some.. have another discord member who reported it. Parameters look fine, i assume it's some account deserialization issue

**Comment by ghost** [comment]
ok.. fixed it.

seems our user emptied his reward token account, and used draffle.io to close his accounts and get his rent back.

now, when claiming or unstaking he had no associated token account for reward, and it failed.

the fix is to recreate the associated token account in the frontend during claim/unstake actions.

**Comment by VegetarianOrc** [comment]
Awesome! Nice sleuthing!
